#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-flexmark-java
Version  : 0.18.4
Release  : 1
URL      : https://github.com/vsch/flexmark-java/archive/0.18.4.tar.gz
Source0  : https://github.com/vsch/flexmark-java/archive/0.18.4.tar.gz
Source1  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-all/0.18.4/flexmark-all-0.18.4.jar
Source2  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-all/0.18.4/flexmark-all-0.18.4.pom
Source3  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-abbreviation/0.18.4/flexmark-ext-abbreviation-0.18.4.jar
Source4  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-abbreviation/0.18.4/flexmark-ext-abbreviation-0.18.4.pom
Source5  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.18.4/flexmark-ext-anchorlink-0.18.4.jar
Source6  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.18.4/flexmark-ext-anchorlink-0.18.4.pom
Source7  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-aside/0.18.4/flexmark-ext-aside-0.18.4.jar
Source8  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-aside/0.18.4/flexmark-ext-aside-0.18.4.pom
Source9  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.18.4/flexmark-ext-autolink-0.18.4.jar
Source10  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.18.4/flexmark-ext-autolink-0.18.4.pom
Source11  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-definition/0.18.4/flexmark-ext-definition-0.18.4.jar
Source12  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-definition/0.18.4/flexmark-ext-definition-0.18.4.pom
Source13  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.18.4/flexmark-ext-emoji-0.18.4.jar
Source14  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.18.4/flexmark-ext-emoji-0.18.4.pom
Source15  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-escaped-character/0.18.4/flexmark-ext-escaped-character-0.18.4.jar
Source16  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-escaped-character/0.18.4/flexmark-ext-escaped-character-0.18.4.pom
Source17  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-footnotes/0.18.4/flexmark-ext-footnotes-0.18.4.jar
Source18  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-footnotes/0.18.4/flexmark-ext-footnotes-0.18.4.pom
Source19  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.18.4/flexmark-ext-gfm-strikethrough-0.18.4.jar
Source20  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.18.4/flexmark-ext-gfm-strikethrough-0.18.4.pom
Source21  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.18.4/flexmark-ext-gfm-tables-0.18.4.jar
Source22  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.18.4/flexmark-ext-gfm-tables-0.18.4.pom
Source23  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.18.4/flexmark-ext-gfm-tasklist-0.18.4.jar
Source24  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.18.4/flexmark-ext-gfm-tasklist-0.18.4.pom
Source25  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.18.4/flexmark-ext-ins-0.18.4.jar
Source26  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.18.4/flexmark-ext-ins-0.18.4.pom
Source27  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-jekyll-front-matter/0.18.4/flexmark-ext-jekyll-front-matter-0.18.4.jar
Source28  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-jekyll-front-matter/0.18.4/flexmark-ext-jekyll-front-matter-0.18.4.pom
Source29  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-jekyll-tag/0.18.4/flexmark-ext-jekyll-tag-0.18.4.jar
Source30  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-jekyll-tag/0.18.4/flexmark-ext-jekyll-tag-0.18.4.pom
Source31  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-spec-example/0.18.4/flexmark-ext-spec-example-0.18.4.jar
Source32  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-spec-example/0.18.4/flexmark-ext-spec-example-0.18.4.pom
Source33  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.18.4/flexmark-ext-superscript-0.18.4.jar
Source34  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.18.4/flexmark-ext-superscript-0.18.4.pom
Source35  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.18.4/flexmark-ext-tables-0.18.4.jar
Source36  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.18.4/flexmark-ext-tables-0.18.4.pom
Source37  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-toc/0.18.4/flexmark-ext-toc-0.18.4.jar
Source38  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-toc/0.18.4/flexmark-ext-toc-0.18.4.pom
Source39  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-typographic/0.18.4/flexmark-ext-typographic-0.18.4.jar
Source40  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-typographic/0.18.4/flexmark-ext-typographic-0.18.4.pom
Source41  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.18.4/flexmark-ext-wikilink-0.18.4.jar
Source42  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.18.4/flexmark-ext-wikilink-0.18.4.pom
Source43  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-xwiki-macros/0.18.4/flexmark-ext-xwiki-macros-0.18.4.jar
Source44  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-xwiki-macros/0.18.4/flexmark-ext-xwiki-macros-0.18.4.pom
Source45  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.18.4/flexmark-ext-yaml-front-matter-0.18.4.jar
Source46  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.18.4/flexmark-ext-yaml-front-matter-0.18.4.pom
Source47  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-formatter/0.18.4/flexmark-formatter-0.18.4.jar
Source48  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-formatter/0.18.4/flexmark-formatter-0.18.4.pom
Source49  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-html-parser/0.18.4/flexmark-html-parser-0.18.4.jar
Source50  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-html-parser/0.18.4/flexmark-html-parser-0.18.4.pom
Source51  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-java/0.18.4/flexmark-java-0.18.4.pom
Source52  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.18.4/flexmark-jira-converter-0.18.4.jar
Source53  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.18.4/flexmark-jira-converter-0.18.4.pom
Source54  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-pdf-converter/0.18.4/flexmark-pdf-converter-0.18.4.jar
Source55  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-pdf-converter/0.18.4/flexmark-pdf-converter-0.18.4.pom
Source56  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-profile-pegdown/0.18.4/flexmark-profile-pegdown-0.18.4.jar
Source57  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-profile-pegdown/0.18.4/flexmark-profile-pegdown-0.18.4.pom
Source58  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-test-util/0.18.4/flexmark-test-util-0.18.4.jar
Source59  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-test-util/0.18.4/flexmark-test-util-0.18.4.pom
Source60  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util/0.18.4/flexmark-util-0.18.4.jar
Source61  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util/0.18.4/flexmark-util-0.18.4.pom
Source62  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-youtrack-converter/0.18.4/flexmark-youtrack-converter-0.18.4.jar
Source63  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-youtrack-converter/0.18.4/flexmark-youtrack-converter-0.18.4.pom
Source64  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.18.4/flexmark-0.18.4.jar
Source65  : https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.18.4/flexmark-0.18.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mvn-flexmark-java-data = %{version}-%{release}

%description
![Flexmark Icon Logo](/assets/images/flexmark-icon-logo%402x.png) flexmark-java
===============================================================================

%package data
Summary: data components for the mvn-flexmark-java package.
Group: Data

%description data
data components for the mvn-flexmark-java package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-all/0.18.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-all/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-all/0.18.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-all/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-abbreviation/0.18.4
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-abbreviation/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-abbreviation/0.18.4
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-abbreviation/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-anchorlink/0.18.4
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-anchorlink/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-anchorlink/0.18.4
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-anchorlink/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-aside/0.18.4
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-aside/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-aside/0.18.4
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-aside/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-autolink/0.18.4
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-autolink/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-autolink/0.18.4
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-autolink/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-definition/0.18.4
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-definition/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-definition/0.18.4
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-definition/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-emoji/0.18.4
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-emoji/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-emoji/0.18.4
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-emoji/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-escaped-character/0.18.4
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-escaped-character/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-escaped-character/0.18.4
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-escaped-character/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-footnotes/0.18.4
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-footnotes/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-footnotes/0.18.4
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-footnotes/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.18.4
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.18.4
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.18.4
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.18.4
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.18.4
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.18.4
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-ins/0.18.4
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-ins/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-ins/0.18.4
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-ins/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-front-matter/0.18.4
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-front-matter/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-front-matter/0.18.4
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-front-matter/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-tag/0.18.4
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-tag/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-tag/0.18.4
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-tag/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-spec-example/0.18.4
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-spec-example/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-spec-example/0.18.4
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-spec-example/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-superscript/0.18.4
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-superscript/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-superscript/0.18.4
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-superscript/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-tables/0.18.4
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-tables/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-tables/0.18.4
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-tables/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-toc/0.18.4
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-toc/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-toc/0.18.4
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-toc/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-typographic/0.18.4
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-typographic/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-typographic/0.18.4
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-typographic/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-wikilink/0.18.4
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-wikilink/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-wikilink/0.18.4
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-wikilink/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-xwiki-macros/0.18.4
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-xwiki-macros/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-xwiki-macros/0.18.4
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-xwiki-macros/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.18.4
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.18.4
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-formatter/0.18.4
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-formatter/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-formatter/0.18.4
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-formatter/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-html-parser/0.18.4
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-html-parser/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-html-parser/0.18.4
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-html-parser/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-java/0.18.4
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-java/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-jira-converter/0.18.4
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-jira-converter/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-jira-converter/0.18.4
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-jira-converter/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-pdf-converter/0.18.4
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-pdf-converter/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-pdf-converter/0.18.4
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-pdf-converter/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-profile-pegdown/0.18.4
cp %{SOURCE56} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-profile-pegdown/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-profile-pegdown/0.18.4
cp %{SOURCE57} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-profile-pegdown/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-test-util/0.18.4
cp %{SOURCE58} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-test-util/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-test-util/0.18.4
cp %{SOURCE59} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-test-util/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-util/0.18.4
cp %{SOURCE60} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-util/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-util/0.18.4
cp %{SOURCE61} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-util/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-youtrack-converter/0.18.4
cp %{SOURCE62} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-youtrack-converter/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-youtrack-converter/0.18.4
cp %{SOURCE63} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-youtrack-converter/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark/0.18.4
cp %{SOURCE64} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark/0.18.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark/0.18.4
cp %{SOURCE65} %{buildroot}/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark/0.18.4


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-all/0.18.4/flexmark-all-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-all/0.18.4/flexmark-all-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-abbreviation/0.18.4/flexmark-ext-abbreviation-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-abbreviation/0.18.4/flexmark-ext-abbreviation-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-anchorlink/0.18.4/flexmark-ext-anchorlink-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-anchorlink/0.18.4/flexmark-ext-anchorlink-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-aside/0.18.4/flexmark-ext-aside-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-aside/0.18.4/flexmark-ext-aside-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-autolink/0.18.4/flexmark-ext-autolink-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-autolink/0.18.4/flexmark-ext-autolink-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-definition/0.18.4/flexmark-ext-definition-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-definition/0.18.4/flexmark-ext-definition-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-emoji/0.18.4/flexmark-ext-emoji-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-emoji/0.18.4/flexmark-ext-emoji-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-escaped-character/0.18.4/flexmark-ext-escaped-character-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-escaped-character/0.18.4/flexmark-ext-escaped-character-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-footnotes/0.18.4/flexmark-ext-footnotes-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-footnotes/0.18.4/flexmark-ext-footnotes-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.18.4/flexmark-ext-gfm-strikethrough-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.18.4/flexmark-ext-gfm-strikethrough-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.18.4/flexmark-ext-gfm-tables-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.18.4/flexmark-ext-gfm-tables-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.18.4/flexmark-ext-gfm-tasklist-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.18.4/flexmark-ext-gfm-tasklist-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-ins/0.18.4/flexmark-ext-ins-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-ins/0.18.4/flexmark-ext-ins-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-front-matter/0.18.4/flexmark-ext-jekyll-front-matter-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-front-matter/0.18.4/flexmark-ext-jekyll-front-matter-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-tag/0.18.4/flexmark-ext-jekyll-tag-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-tag/0.18.4/flexmark-ext-jekyll-tag-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-spec-example/0.18.4/flexmark-ext-spec-example-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-spec-example/0.18.4/flexmark-ext-spec-example-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-superscript/0.18.4/flexmark-ext-superscript-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-superscript/0.18.4/flexmark-ext-superscript-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-tables/0.18.4/flexmark-ext-tables-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-tables/0.18.4/flexmark-ext-tables-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-toc/0.18.4/flexmark-ext-toc-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-toc/0.18.4/flexmark-ext-toc-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-typographic/0.18.4/flexmark-ext-typographic-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-typographic/0.18.4/flexmark-ext-typographic-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-wikilink/0.18.4/flexmark-ext-wikilink-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-wikilink/0.18.4/flexmark-ext-wikilink-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-xwiki-macros/0.18.4/flexmark-ext-xwiki-macros-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-xwiki-macros/0.18.4/flexmark-ext-xwiki-macros-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.18.4/flexmark-ext-yaml-front-matter-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.18.4/flexmark-ext-yaml-front-matter-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-formatter/0.18.4/flexmark-formatter-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-formatter/0.18.4/flexmark-formatter-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-html-parser/0.18.4/flexmark-html-parser-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-html-parser/0.18.4/flexmark-html-parser-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-java/0.18.4/flexmark-java-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-jira-converter/0.18.4/flexmark-jira-converter-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-jira-converter/0.18.4/flexmark-jira-converter-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-pdf-converter/0.18.4/flexmark-pdf-converter-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-pdf-converter/0.18.4/flexmark-pdf-converter-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-profile-pegdown/0.18.4/flexmark-profile-pegdown-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-profile-pegdown/0.18.4/flexmark-profile-pegdown-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-test-util/0.18.4/flexmark-test-util-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-test-util/0.18.4/flexmark-test-util-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-util/0.18.4/flexmark-util-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-util/0.18.4/flexmark-util-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-youtrack-converter/0.18.4/flexmark-youtrack-converter-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark-youtrack-converter/0.18.4/flexmark-youtrack-converter-0.18.4.pom
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark/0.18.4/flexmark-0.18.4.jar
/usr/share/java/.m2/repository/com/vladsch/flexmark/flexmark/0.18.4/flexmark-0.18.4.pom
